export const DEFAULT_TIMEOUT_MS = 5000;
export const DEFAULT_IDLE_TIMEOUT_MS = 5000;
export const MAX_CONNECTIONS = 20;
export const MAX_QUEUE_CONNECTIONS = 20;
export const KEEP_ALIVE_INITIAL_DELAY = 0;